---
title: "Dataanalysportfolio"
---


## Om projektet

Denna portfolio presenterar en analys av globala samhällsindikatorer utifrån data från organisationen Our World in Data.

Syftet är att demonstrera ett komplett dataanalysflöde i form av:

- insamling och bearbetning av data
- explorativ dataanalys genom korrelationsanalys och datavisualisering
- fördjupade analyser genom multipel regression och prediktiv maskininlärning

All dataanalys är gjord i Python och rapporten är skapad med Quarto.

## Data

Samtliga projekt utgår från en databas som sammanställdes utifrån 23 separata dataset från [Our World in Data](https://ourworldindata.org/), vilket är en organisation som sammanställer och visualiserar historisk och globalt täckande statistik inom områden som fattigdom, sjukdom, hunger, klimatförändringar, krig och ojämlikhet. Den data de sammanställer kommer från flera olika källor.


## Analysfrågor

Projektet undersöker bland annat:

- Hur samvarierar olika samhällsindikatorer på nationsnivå?
- Vilka faktorer är associerade med länders demokratiindex?
- Hur väl går det att predicera huruvida länder är demokratier utifrån kännedom om andra faktorer?
